#! /bin/sh

desktops=3 # How many desktops to move to the second monitor

monitor_add() {
	for desktop in $(bspc query -D -m $INT_MONITOR | sed "$desktops"q);
  	do
		bspc desktop $desktop --to-monitor $EXT_MONITOR
  	done
	
  	bspc desktop Desktop --remove
	bspc monitor $EXT_MONITOR --reorder-desktops 1 2 3
    bspc wm -O $EXT_MONITOR $INT_MONITOR
}

monitor_remove() {
    # add temp desktop, cause bspwm monitors have to have min 1 desktop
	bspc monitor $EXT_MONITOR -a Desktop
    # move all desktops except last to internal monitor
	for desktop in $(bspc query -D -m $EXT_MONITOR); do
		bspc desktop $desktop --to-monitor $INT_MONITOR
	done
    
    # remove ext monitor
    bspc monitor $EXT_MONITOR --remove
    # delete default desktop
	bspc desktop Desktop --remove
  	bspc monitor $INT_MONITOR --reorder-desktops 1 2 3 4 5 6
}

if [[ $(autorandr | grep "external (detected)") ]]; then
    monitor_add
else
    monitor_remove
fi


xwallpaper --zoom ~/.config/wall.png
$HOME/.config/polybar/launch.sh
