#! /bin/sh

if [[ $(autorandr | grep 'sillamae (detected)') ]]; 
then
	bspc monitor DP-3-1-8 -d 1 2 3 &
	bspc monitor DP-3-8 -d 4 5 6 &

	bspc monitor eDP-1 --remove &
else
	bspc monitor eDP-1 -d 1 2 3 4 5 6 &
fi

pggrep -x sxhkd >/dev/null || sxhkd &
$HOME/.local/bin/startup &

bspc config window_gap 11
bspc config top_padding -11

bspc config split_ratio 0.60

# Monocle Mode
bspc config gapless_monocle true
bspc config top_monocle_padding 11

bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true
