#! /bin/sh

pggrep -x sxhkd >/dev/null || sxhkd &
bspc monitor eDP-1 -d 1 2 3 4 &
bspc monitor HDMI-1 -d 5 6 7 8 &
$HOME/.local/bin/startup

bspc config border_width 0 
bspc config window_gap 12
bspc config top_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config bottom_padding 0

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
