#! /bin/sh

if [[ $(autorandr | grep 'sillamae (detected)') ]]; then
	bspc monitor $SECOND_EXT_MONITOR -d 1 2 3
	bspc monitor $EXT_MONITOR -d 4 5 6

	bspc monitor $INT_MONITOR --remove

elif [[ $(autorandr | grep 'home (detected)') ]]; then
	xrandr --output $EXT_MONITOR --primary
	bspc monitor $INT_MONITOR -d 1 2 3
	bspc monitor $EXT_MONITOR -d 4 5 6

else
	bspc monitor $INT_MONITOR -d 1 2 3 4 5 6
fi


pgrep -x sxhkd >/dev/null || sxhkd
xwallpaper --zoom ~/.config/wall.jpg
$HOME/.config/polybar/launch.sh


# Bspwm Config

bspc config window_gap 7
#bspc config top_padding -3
#bspc config left_padding -7
#bspc config right_padding -7 
#bspc config bottom_padding -7
bspc config split_ratio 0.50

# Monocle Mode
bspc config gapless_monocle true
bspc config borderless_monocle true
# bspc config top_monocle_padding 5

bspc config remove_disabled_monitors true
# bspc config merge_overlapping_monitors true
